version: 2
jobs:
  build_test:
    docker:
     - image: ubuntu:20.04
    steps:
     # install dependencies
     - run: apt-get -y update &&
            apt-get -y install cmake g++
     - checkout
     - run: mkdir build
     - run: cd build && cmake -DCMAKE_BUILD_TYPE=debug ..
     - run: cd build && make -j
     #- run: cd build && make check-lint
     #- run: cd build && make check-clang-tidy
     #- run: cd build && make check-tests

workflows:
  version: 2
  workflow:
    jobs:
      - build_test
