version: 2
jobs:
  build_test:
    docker:
     - image: ubuntu:20.04
    steps:
     # install dependencies
     - run: apt-get -y update &&
            DEBIAN_FRONTEND=noninteractive apt-get -y install 
            cmake
            clang-8
            clang-format-8
            clang-tidy-8
            g++
            git
            valgrind
            python
     - checkout
     - run: mkdir build
     - run: cd build && cmake -DCMAKE_BUILD_TYPE=debug ..
     - run: cd build && make -j
     - run: cd build && make check-format
     #- run: cd build && make check-clang-tidy
     #- run: cd build && make check-tests

workflows:
  version: 2
  workflow:
    jobs:
      - build_test
